[book]
authors = ["Shiwei Weng 翁士伟"]
language = "en"
multilingual = true
src = "src"
title = "Fairyland OCaml"

[output.html]
mathjax-support = true
additional-js = ["asset/mermaid.min.js", "asset/mermaid-init.js"]

[preprocessor.graphviz]
command = "mdbook-graphviz"

[preprocessor.mermaid]
command = "mdbook-mermaid"
